/* generated by build-site.js */
const CACHE = 'tms-cc3cbf11fa';
const ASSETS = ["./","index.html","styles.css","app.js","gate.js","vocab.js","videos.js","manifest.webmanifest","icons/apple-touch-icon.png","icons/icon-192.png","icons/icon-512.png","courses/registry.js","courses/economics/course.js","courses/economics/manifest.js","courses/economics/lessons/w01.js","courses/economics/lessons/w02.js","courses/marketing/course.js","courses/marketing/manifest.js","courses/marketing/lessons/w01.js","courses/marketing/lessons/w02.js"];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k !== CACHE && k !== VIDEO_CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

const VIDEO_CACHE = 'tms-video';

/* A lecture the user chose to keep. Served from the cache, with byte ranges
   answered properly — without that, Safari refuses to play an offline video
   and seeking does not work anywhere. */
async function fromVideoCache(request) {
  const c = await caches.open(VIDEO_CACHE);
  const hit = await c.match(request.url, { ignoreSearch: true });
  if (!hit) return fetch(request);
  const range = request.headers.get('range');
  if (!range) return hit;
  const buf = await hit.arrayBuffer();
  const m = /bytes=(d*)-(d*)/.exec(range) || [];
  const start = m[1] ? parseInt(m[1], 10) : 0;
  const end = m[2] ? parseInt(m[2], 10) : buf.byteLength - 1;
  if (start >= buf.byteLength) {
    return new Response(null, { status: 416, headers: { 'Content-Range': 'bytes */' + buf.byteLength } });
  }
  return new Response(buf.slice(start, end + 1), {
    status: 206,
    headers: {
      'Content-Type': 'video/mp4',
      'Content-Range': 'bytes ' + start + '-' + end + '/' + buf.byteLength,
      'Content-Length': String(end - start + 1),
      'Accept-Ranges': 'bytes'
    }
  });
}

self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  const url = new URL(e.request.url);
  if (url.origin !== location.origin) return;            // fonts go to the network
  if (url.pathname.indexOf('/video/') >= 0) {            // saved lectures only; the rest stream
    e.respondWith(fromVideoCache(e.request));
    return;
  }
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then(hit => hit || fetch(e.request)
      .then(res => {
        if (res && res.ok) { const copy = res.clone(); caches.open(CACHE).then(c => c.put(e.request, copy)); }
        return res;
      })
      .catch(() => caches.match('index.html')))
  );
});
