/* generated by build-site.js */
window.VIDEOS = {
  "economics.w01l01": {
    "src": "video/economics-w01l01.mp4",
    "mb": 10.5
  },
  "economics.w01l02": {
    "src": "video/economics-w01l02.mp4",
    "mb": 11.4
  },
  "economics.w01l03": {
    "src": "video/economics-w01l03.mp4",
    "mb": 12.2
  },
  "economics.w01l04": {
    "src": "video/economics-w01l04.mp4",
    "mb": 10.9
  },
  "economics.w01l05": {
    "src": "video/economics-w01l05.mp4",
    "mb": 11.4
  },
  "economics.w02l01": {
    "src": "video/economics-w02l01.mp4",
    "mb": 11.8
  },
  "economics.w02l02": {
    "src": "video/economics-w02l02.mp4",
    "mb": 11.5
  },
  "economics.w02l03": {
    "src": "video/economics-w02l03.mp4",
    "mb": 11.2
  },
  "economics.w02l04": {
    "src": "video/economics-w02l04.mp4",
    "mb": 11.9
  },
  "economics.w02l05": {
    "src": "video/economics-w02l05.mp4",
    "mb": 12.2
  },
  "marketing.w01l01": {
    "src": "video/marketing-w01l01.mp4",
    "mb": 10
  },
  "marketing.w01l02": {
    "src": "video/marketing-w01l02.mp4",
    "mb": 11.1
  },
  "marketing.w01l03": {
    "src": "video/marketing-w01l03.mp4",
    "mb": 9.6
  },
  "marketing.w01l04": {
    "src": "video/marketing-w01l04.mp4",
    "mb": 22.1
  },
  "marketing.w01l05": {
    "src": "video/marketing-w01l05.mp4",
    "mb": 9.2
  },
  "marketing.w02l01": {
    "src": "video/marketing-w02l01.mp4",
    "mb": 9.1
  },
  "marketing.w02l02": {
    "src": "video/marketing-w02l02.mp4",
    "mb": 8.8
  },
  "marketing.w02l03": {
    "src": "video/marketing-w02l03.mp4",
    "mb": 12.3
  },
  "marketing.w02l04": {
    "src": "video/marketing-w02l04.mp4",
    "mb": 13.2
  },
  "marketing.w02l05": {
    "src": "video/marketing-w02l05.mp4",
    "mb": 12.7
  }
};
