/* English → Estonian, for the words an academic lecture leans on.
   One dictionary for every course and every lecture: words repeat, so this
   grows slowly and pays off across all eighty. Each entry is [Estonian, plain English].
   Marketing's own terms are NOT here — those come from each lecture's glossary. */
window.VOCAB = (function () {
  var d = {
    abandon: ["hülgama, loobuma", "to stop doing something and leave it behind"],
    absorb: ["neelama, endasse võtma", "to take something in"],
    abstract: ["abstraktne", "about ideas rather than things you can touch"],
    accumulate: ["kogunema", "to build up over time"],
    acquire: ["omandama, hankima", "to get or gain something"],
    adequate: ["piisav", "enough, but only just"],
    adjacent: ["külgnev, naaber-", "next to something"],
    aggregate: ["kogusumma, koond-", "everything added together"],
    allocate: ["jaotama, eraldama", "to decide how much of something goes where"],
    ambiguous: ["mitmetähenduslik", "can be understood in more than one way"],
    anticipate: ["ette aimama", "to expect something and prepare for it"],
    apparent: ["näiline; ilmne", "seeming to be true — sometimes really true, sometimes only on the surface"],
    arbitrary: ["suvaline", "chosen without a real reason"],
    assert: ["väitma, kinnitama", "to state something firmly as true"],
    assess: ["hindama", "to judge how good or how big something is"],
    assume: ["eeldama", "to believe something without checking it"],
    attribute: ["omistama; omadus", "to say what caused something; or a quality something has"],
    audit: ["auditeerima, üle vaatama", "to check something carefully and officially"],
    aversion: ["vastumeelsus", "a strong dislike"],
    bargain: ["kaubelnud; soodne ost", "to argue about a price; or a thing bought cheaply"],
    benchmark: ["võrdlusalus", "a standard you measure yourself against"],
    bias: ["kallutatus", "a leaning towards one answer that stops you seeing straight"],
    boundary: ["piir", "the line where one thing ends and another begins"],
    burden: ["koorem", "a heavy thing you have to carry or pay"],
    capture: ["haarama, kinni püüdma", "to take and keep something"],
    cease: ["lakkama", "to stop"],
    coherent: ["sidus, loogiline", "the parts fit together and make sense"],
    commodity: ["kaup, tooraine", "a basic product where one seller's is the same as another's"],
    compensate: ["hüvitama; korvama", "to make up for something"],
    competent: ["pädev", "able to do the job properly"],
    complement: ["täiendama", "to go well with something and make it more complete"],
    comply: ["järgima, täitma", "to do what a rule says"],
    component: ["komponent, osa", "one part of a bigger thing"],
    comprise: ["koosnema", "to be made up of"],
    confirm: ["kinnitama", "to show something is true"],
    consent: ["nõusolek", "agreeing to let something happen"],
    consequence: ["tagajärg", "what happens as a result"],
    considerable: ["märkimisväärne", "large enough to matter"],
    consistent: ["järjekindel, kooskõlaline", "always the same, or not contradicting itself"],
    constrain: ["piirama", "to limit what someone can do"],
    consumption: ["tarbimine", "using something up"],
    contradict: ["vastu rääkima", "to say the opposite of"],
    contrary: ["vastupidine", "the opposite"],
    controversial: ["vastuoluline", "people strongly disagree about it"],
    convention: ["tava, kokkulepe", "the usual way of doing something, agreed rather than proved"],
    convert: ["muundama; pöörama", "to change into something else"],
    convince: ["veenma", "to make someone believe you"],
    credible: ["usutav", "believable"],
    criterion: ["kriteerium", "a standard you judge by"],
    crucial: ["otsustav, ülioluline", "so important that everything depends on it"],
    cumulative: ["kuhjuv", "growing by adding each new amount to the last"],
    decline: ["langus; langema; keelduma", "a fall; to fall; or to say no"],
    deduce: ["järeldama", "to work out from what you already know"],
    deficit: ["puudujääk", "less money coming in than going out"],
    deliberate: ["tahtlik, teadlik", "done on purpose after thinking"],
    demonstrate: ["näitama, tõestama", "to show clearly"],
    deprive: ["ilma jätma", "to take something away from someone who needs it"],
    derive: ["tuletama; pärinema", "to get one thing from another"],
    deteriorate: ["halvenema", "to get worse"],
    deviate: ["kõrvale kalduma", "to go away from the usual path"],
    devise: ["välja mõtlema", "to invent a plan or method"],
    diminish: ["vähenema", "to get smaller"],
    discourage: ["pärssima, heidutama", "to make someone less likely to do something"],
    discrete: ["eraldiseisev", "separate, not joined to the others"],
    displace: ["välja tõrjuma", "to push something out of its place"],
    distort: ["moonutama", "to change the shape of the truth"],
    diverge: ["lahknema", "to move apart"],
    diverse: ["mitmekesine", "of many different kinds"],
    domain: ["valdkond", "an area of activity or knowledge"],
    dominate: ["domineerima", "to be much stronger than everything else"],
    elaborate: ["põhjalik; lahti seletama", "detailed; or to explain in more detail"],
    eliminate: ["kõrvaldama", "to remove completely"],
    embed: ["sisse põimima", "to fix something firmly inside something else"],
    emerge: ["esile kerkima", "to appear, often slowly"],
    empirical: ["empiiriline", "based on what was observed, not on theory"],
    enable: ["võimaldama", "to make something possible"],
    encounter: ["kohtama", "to meet or come across"],
    endure: ["kestma; taluma", "to last a long time; or to put up with"],
    enhance: ["parandama, võimendama", "to make better or stronger"],
    ensure: ["tagama", "to make certain"],
    entail: ["endaga kaasa tooma", "to necessarily involve"],
    equivalent: ["samaväärne", "equal in value or meaning"],
    erode: ["kulutama, õõnestama", "to wear away slowly"],
    establish: ["kindlaks tegema; rajama", "to prove; or to set up"],
    estimate: ["hinnanguliselt arvutama", "a rough calculation"],
    evaluate: ["hindama", "to judge the value of"],
    eventual: ["lõplik, lõpuks saabuv", "happening in the end"],
    evident: ["ilmne", "easy to see"],
    exceed: ["ületama", "to be more than"],
    exclude: ["välja jätma", "to leave out"],
    exert: ["rakendama, avaldama", "to apply force or influence"],
    explicit: ["selgesõnaline", "said openly, leaving nothing to be guessed"],
    exploit: ["ära kasutama", "to use something fully — or to use someone unfairly"],
    expose: ["paljastama; kokku puutuma", "to uncover; or to bring into contact with"],
    facilitate: ["hõlbustama", "to make easier"],
    feasible: ["teostatav", "possible to do"],
    finite: ["piiratud, lõplik", "having an end; not unlimited"],
    fluctuate: ["kõikuma", "to go up and down"],
    forecast: ["prognoos", "a statement about what will happen"],
    formulate: ["sõnastama", "to put into a clear form of words"],
    fundamental: ["põhiline, alusepanev", "the most basic and important"],
    generate: ["tekitama, looma", "to make or produce"],
    genuine: ["tõeline, ehtne", "real, not fake"],
    guarantee: ["tagatis, garantii", "a firm promise"],
    hierarchy: ["hierarhia, astmestik", "an order from highest to lowest"],
    hypothesis: ["hüpotees", "an idea you test to see if it is true"],
    identical: ["identne, täpselt sama", "exactly the same"],
    illustrate: ["näitlikustama", "to make clear with an example"],
    imitate: ["jäljendama", "to copy"],
    implement: ["ellu viima, rakendama", "to actually carry out a plan"],
    implicit: ["kaudne, vaikimisi", "not said openly but understood"],
    imply: ["vihjama; tähendama", "to suggest without saying"],
    impose: ["peale suruma, kehtestama", "to force something on someone"],
    incentive: ["stiimul, ajend", "a reason that makes someone want to act"],
    incidence: ["esinemissagedus; langemine kellelegi", "how often something happens; or who really bears a cost"],
    incur: ["endale tekitama", "to bring a cost or loss on yourself"],
    indicate: ["osutama, näitama", "to show or point to"],
    induce: ["esile kutsuma", "to cause something to happen"],
    inevitable: ["vältimatu", "certain to happen; cannot be avoided"],
    infer: ["järeldama", "to work out from evidence"],
    inherent: ["olemuslik, loomuomane", "part of the nature of the thing"],
    inhibit: ["pidurdama", "to hold back"],
    initiate: ["algatama", "to start"],
    insight: ["arusaam, taipamine", "a true understanding that was not obvious"],
    integrate: ["lõimima, ühendama", "to join parts into one whole"],
    interpret: ["tõlgendama", "to decide what something means"],
    intervene: ["sekkuma", "to step in and change what is happening"],
    intrinsic: ["sisemine, olemuslik", "belonging to the thing itself"],
    isolate: ["eraldama", "to separate one thing from everything else"],
    justify: ["põhjendama", "to give good reasons for"],
    legitimate: ["õiguspärane, põhjendatud", "allowed, or reasonable"],
    liable: ["vastutav; kalduv", "legally responsible; or likely to"],
    magnitude: ["suurusjärk", "how big something is"],
    maintain: ["säilitama; väitma", "to keep as it is; or to insist"],
    mandate: ["volitus, mandaat", "official permission or instruction"],
    manipulate: ["manipuleerima", "to control someone unfairly"],
    margin: ["marginaal, vahe", "the gap between price and cost — or a narrow edge"],
    mediate: ["vahendama", "to act between two sides"],
    methodology: ["metoodika", "the set of methods used"],
    mitigate: ["leevendama", "to make less bad"],
    modify: ["muutma, kohandama", "to change slightly"],
    monitor: ["jälgima", "to watch over time"],
    motive: ["ajend, motiiv", "the reason someone does something"],
    mutual: ["vastastikune", "going both ways"],
    negligible: ["tühine", "so small it can be ignored"],
    notion: ["mõte, arusaam", "an idea"],
    obscure: ["ähmane; varjama", "hard to understand; or to hide"],
    obsolete: ["vananenud", "out of date and no longer used"],
    obtain: ["hankima, saama", "to get"],
    offset: ["tasakaalustama", "to cancel out with something on the other side"],
    optimal: ["optimaalne, parim võimalik", "the best possible"],
    outcome: ["tulemus", "what happens in the end"],
    overlap: ["kattuma", "to cover part of the same ground"],
    paradigm: ["paradigma, mõttemudel", "the whole way of thinking a field uses"],
    parameter: ["parameeter, muutuja", "a value you can set that changes the result"],
    partial: ["osaline; erapoolik", "only part of it; or taking one side"],
    perceive: ["tajuma", "to notice or understand through the senses"],
    persist: ["püsima; visalt jätkama", "to keep going or keep existing"],
    perspective: ["vaatenurk", "the point of view something is seen from"],
    pervasive: ["läbiv, kõikjale tungiv", "found everywhere"],
    phenomenon: ["nähtus", "a thing that happens and can be observed"],
    plausible: ["usutav", "sounds reasonable — which is not the same as true"],
    portion: ["osa", "a part of a whole"],
    potential: ["võimalik, potentsiaalne", "possible in the future but not yet real"],
    precede: ["eelnema", "to come before"],
    precise: ["täpne", "exact"],
    preliminary: ["esialgne", "coming first, before the main part"],
    premise: ["eeldus, lähtekoht", "something taken as true to build an argument on"],
    presume: ["eeldama", "to assume something is true"],
    prevail: ["valitsema; peale jääma", "to be most common, or to win in the end"],
    principle: ["põhimõte", "a basic rule that explains many cases"],
    procedure: ["menetlus, protseduur", "the official steps for doing something"],
    prohibit: ["keelama", "to forbid"],
    proportion: ["osakaal, proportsioon", "how big one part is compared with the whole"],
    prospect: ["väljavaade; potentsiaalne klient", "a possible future — or a possible customer"],
    provision: ["säte; varustamine", "a rule in an agreement; or supplying something"],
    pursue: ["taotlema, jälitama", "to chase or try to achieve"],
    qualitative: ["kvalitatiivne", "about qualities and descriptions, not numbers"],
    quantitative: ["kvantitatiivne", "about amounts and numbers"],
    radical: ["radikaalne, juurteni ulatuv", "going all the way to the root; extreme"],
    ratio: ["suhtarv", "one number divided by another"],
    rational: ["ratsionaalne, mõistuspärane", "based on reason"],
    reciprocal: ["vastastikune", "given in return, both ways"],
    reconcile: ["ühitama, lepitama", "to make two things fit together"],
    refine: ["viimistlema, täpsustama", "to improve by small careful changes"],
    refute: ["ümber lükkama", "to prove wrong"],
    reinforce: ["tugevdama", "to make stronger"],
    relevant: ["asjakohane", "connected to what is being discussed, and mattering to it"],
    reluctant: ["tõrges", "unwilling"],
    remedy: ["ravim; lahendus", "the cure or fix"],
    render: ["muutma (milleski); esitama", "to make something become a certain way"],
    residual: ["jääk", "what is left after you subtract everything you can explain"],
    resolve: ["lahendama; otsustavus", "to settle a problem; or firmness of purpose"],
    respective: ["vastav", "each belonging to the one just named"],
    restrain: ["ohjeldama", "to hold back"],
    retain: ["säilitama, alles hoidma", "to keep"],
    reveal: ["paljastama", "to show something that was hidden"],
    revenue: ["tulu, käive", "the money coming in, before costs"],
    rigid: ["jäik", "not able to bend or change"],
    rigour: ["rangus, põhjalikkus", "being careful, exact and honest in method"],
    scarce: ["nappiv, vähene", "not enough to go round"],
    scenario: ["stsenaarium", "one possible way things could turn out"],
    scope: ["ulatus, haare", "how much ground something covers"],
    scrutiny: ["põhjalik kontroll", "close and critical examination"],
    sequence: ["järjestus", "the order things come in"],
    sophisticated: ["keerukas, viimistletud", "advanced and complex"],
    spectrum: ["skaala, spekter", "a full range between two extremes"],
    speculate: ["oletama; spekuleerima", "to guess without evidence"],
    stagnant: ["seisev, paigal tammuv", "not moving or growing"],
    stake: ["panus; osalus", "what you stand to win or lose"],
    stance: ["seisukoht", "the position someone takes"],
    straightforward: ["otsekohene, lihtne", "simple and clear"],
    subordinate: ["alluv; allutatud", "lower in rank, or made less important"],
    subsequent: ["järgnev", "coming after"],
    subsidy: ["toetus, subsiidium", "money the state pays to lower a price"],
    substantial: ["märkimisväärne, sisuline", "large or real enough to matter"],
    subtle: ["peen, raskesti märgatav", "small and easy to miss, but important"],
    sufficient: ["piisav", "enough"],
    superfluous: ["üleliigne", "more than is needed; unnecessary"],
    sustain: ["ülal hoidma, säilitama", "to keep something going"],
    tangible: ["käegakatsutav", "can be touched; real and concrete"],
    tentative: ["esialgne, ettevaatlik", "not final; held lightly"],
    threshold: ["lävi, künnis", "the point at which something starts to happen"],
    transfer: ["ülekanne, üle kandma", "to move from one place or context to another"],
    transition: ["üleminek", "the change from one state to another"],
    trigger: ["vallandama; päästik", "to set off; or the thing that sets it off"],
    trivial: ["tühine", "so small or obvious it does not matter"],
    ultimate: ["lõplik, kõige tähtsam", "final, or most important"],
    undergo: ["läbi tegema", "to go through something, usually unpleasant"],
    underlying: ["aluseks olev", "hidden beneath, and causing what you can see"],
    undertake: ["ette võtma", "to take on a task"],
    unprecedented: ["enneolematu", "never having happened before"],
    valid: ["kehtiv, põhjendatud", "correctly reasoned, or legally in force"],
    viable: ["elujõuline", "able to work and survive"],
    violate: ["rikkuma", "to break a rule or agreement"],
    voluntary: ["vabatahtlik", "done by choice, not forced"],
    widespread: ["laialt levinud", "found over a wide area"],
    yield: ["andma, tootma; järele andma", "to produce a result; or to give way"],

    /* words this course leans on especially hard */
    myopia: ["lühinägelikkus", "short-sightedness — seeing what is close and missing what is further"],
    hyperopia: ["kaugnägelikkus", "long-sightedness — the opposite error"],
    incumbent: ["turgu valitsev olemasolev ettevõte", "the company already holding the market"],
    complacency: ["eneserahulolu", "feeling safe when you have no good reason to be"],
    deception: ["pettus", "making someone believe something untrue"],
    diagnose: ["diagnoosima", "to work out what is actually wrong, the way a doctor does"],
    diagnostic: ["diagnostiline vahend", "a tool for finding out what is wrong"],
    intermediary: ["vahendaja", "someone in the middle between maker and buyer"],
    procurement: ["hanked, ostuosakond", "the formal process organisations use to buy things"],
    endorsement: ["heakskiit, soovitus", "a public statement of support that lends you trust"],
    sceptical: ["skeptiline, kahtlev", "not easily convinced; wanting proof"],
    stalled: ["takerdunud", "stopped making progress without anyone deciding to stop"],
    exchange: ["vahetus", "two parties each giving the other something they value more"],
    offering: ["pakkumine", "whatever you put in front of someone: product, service, idea"],
    discipline: ["valdkond, distsipliin", "a field of study with its own methods"],
    compounding: ["liitumine, kuhjumine", "growth that multiplies each period instead of adding"],
    exponent: ["astendaja", "the small raised number saying how many times to multiply"],
    logarithm: ["logaritm", "the tool that answers: how many times must I multiply by this?"],
    denominator: ["nimetaja", "the bottom number of a fraction — what you are dividing by"],
    numerator: ["lugeja", "the top number of a fraction"],
    elasticity: ["elastsus", "how much one thing changes when another changes"],
    externality: ["välismõju", "a cost or benefit falling on someone outside the deal"],
    proxy: ["asendusnäitaja", "something measurable you use to stand for something you cannot measure"],
    heuristic: ["rusikareegel", "a mental shortcut that is usually good enough"],
    salience: ["esiletulevus, meeldejäävus", "how easily something comes to mind"],
    attrition: ["kulumine, äravool", "steady loss over time"],
    leverage: ["finantsvõimendus; mõjujõud", "using borrowed money; or the power to move something"],
    arbitrage: ["arbitraaž", "buying cheap in one place and selling dear in another"]
  };
  /* index is lower-case; simple endings are matched at look-up time */
  var out = {};
  Object.keys(d).forEach(function (k) { out[k] = { et: d[k][0], en: d[k][1] }; });
  return out;
})();
