/* English → Estonian, for the words an academic lecture leans on.
   One dictionary for every course and every lecture: words repeat, so this
   grows slowly and pays off across all eighty. Each entry is [Estonian, plain English].
   Marketing's own terms are NOT here — those come from each lecture's glossary. */
window.VOCAB = (function () {
  var d = {
    abandon: ["hülgama, loobuma", "to stop doing something and leave it behind"],
    absorb: ["neelama, endasse võtma", "to take something in"],
    abstract: ["abstraktne", "about ideas rather than things you can touch"],
    accumulate: ["kogunema", "to build up over time"],
    acquire: ["omandama, hankima", "to get or gain something"],
    adequate: ["piisav", "enough, but only just"],
    adjacent: ["külgnev, naaber-", "next to something"],
    aggregate: ["kogusumma, koond-", "everything added together"],
    allocate: ["jaotama, eraldama", "to decide how much of something goes where"],
    ambiguous: ["mitmetähenduslik", "can be understood in more than one way"],
    anticipate: ["ette aimama", "to expect something and prepare for it"],
    apparent: ["näiline; ilmne", "seeming to be true — sometimes really true, sometimes only on the surface"],
    arbitrary: ["suvaline", "chosen without a real reason"],
    assert: ["väitma, kinnitama", "to state something firmly as true"],
    assess: ["hindama", "to judge how good or how big something is"],
    assume: ["eeldama", "to believe something without checking it"],
    attribute: ["omistama; omadus", "to say what caused something; or a quality something has"],
    audit: ["auditeerima, üle vaatama", "to check something carefully and officially"],
    aversion: ["vastumeelsus", "a strong dislike"],
    bargain: ["kaubelnud; soodne ost", "to argue about a price; or a thing bought cheaply"],
    benchmark: ["võrdlusalus", "a standard you measure yourself against"],
    bias: ["kallutatus", "a leaning towards one answer that stops you seeing straight"],
    boundary: ["piir", "the line where one thing ends and another begins"],
    burden: ["koorem", "a heavy thing you have to carry or pay"],
    capture: ["haarama, kinni püüdma", "to take and keep something"],
    cease: ["lakkama", "to stop"],
    coherent: ["sidus, loogiline", "the parts fit together and make sense"],
    commodity: ["kaup, tooraine", "a basic product where one seller's is the same as another's"],
    compensate: ["hüvitama; korvama", "to make up for something"],
    competent: ["pädev", "able to do the job properly"],
    complement: ["täiendama", "to go well with something and make it more complete"],
    comply: ["järgima, täitma", "to do what a rule says"],
    component: ["komponent, osa", "one part of a bigger thing"],
    comprise: ["koosnema", "to be made up of"],
    confirm: ["kinnitama", "to show something is true"],
    consent: ["nõusolek", "agreeing to let something happen"],
    consequence: ["tagajärg", "what happens as a result"],
    considerable: ["märkimisväärne", "large enough to matter"],
    consistent: ["järjekindel, kooskõlaline", "always the same, or not contradicting itself"],
    constrain: ["piirama", "to limit what someone can do"],
    consumption: ["tarbimine", "using something up"],
    contradict: ["vastu rääkima", "to say the opposite of"],
    contrary: ["vastupidine", "the opposite"],
    controversial: ["vastuoluline", "people strongly disagree about it"],
    convention: ["tava, kokkulepe", "the usual way of doing something, agreed rather than proved"],
    convert: ["muundama; pöörama", "to change into something else"],
    convince: ["veenma", "to make someone believe you"],
    credible: ["usutav", "believable"],
    criterion: ["kriteerium", "a standard you judge by"],
    crucial: ["otsustav, ülioluline", "so important that everything depends on it"],
    cumulative: ["kuhjuv", "growing by adding each new amount to the last"],
    decline: ["langus; langema; keelduma", "a fall; to fall; or to say no"],
    deduce: ["järeldama", "to work out from what you already know"],
    deficit: ["puudujääk", "less money coming in than going out"],
    deliberate: ["tahtlik, teadlik", "done on purpose after thinking"],
    demonstrate: ["näitama, tõestama", "to show clearly"],
    deprive: ["ilma jätma", "to take something away from someone who needs it"],
    derive: ["tuletama; pärinema", "to get one thing from another"],
    deteriorate: ["halvenema", "to get worse"],
    deviate: ["kõrvale kalduma", "to go away from the usual path"],
    devise: ["välja mõtlema", "to invent a plan or method"],
    diminish: ["vähenema", "to get smaller"],
    discourage: ["pärssima, heidutama", "to make someone less likely to do something"],
    discrete: ["eraldiseisev", "separate, not joined to the others"],
    displace: ["välja tõrjuma", "to push something out of its place"],
    distort: ["moonutama", "to change the shape of the truth"],
    diverge: ["lahknema", "to move apart"],
    diverse: ["mitmekesine", "of many different kinds"],
    domain: ["valdkond", "an area of activity or knowledge"],
    dominate: ["domineerima", "to be much stronger than everything else"],
    elaborate: ["põhjalik; lahti seletama", "detailed; or to explain in more detail"],
    eliminate: ["kõrvaldama", "to remove completely"],
    embed: ["sisse põimima", "to fix something firmly inside something else"],
    emerge: ["esile kerkima", "to appear, often slowly"],
    empirical: ["empiiriline", "based on what was observed, not on theory"],
    enable: ["võimaldama", "to make something possible"],
    encounter: ["kohtama", "to meet or come across"],
    endure: ["kestma; taluma", "to last a long time; or to put up with"],
    enhance: ["parandama, võimendama", "to make better or stronger"],
    ensure: ["tagama", "to make certain"],
    entail: ["endaga kaasa tooma", "to necessarily involve"],
    equivalent: ["samaväärne", "equal in value or meaning"],
    erode: ["kulutama, õõnestama", "to wear away slowly"],
    establish: ["kindlaks tegema; rajama", "to prove; or to set up"],
    estimate: ["hinnanguliselt arvutama", "a rough calculation"],
    evaluate: ["hindama", "to judge the value of"],
    eventual: ["lõplik, lõpuks saabuv", "happening in the end"],
    evident: ["ilmne", "easy to see"],
    exceed: ["ületama", "to be more than"],
    exclude: ["välja jätma", "to leave out"],
    exert: ["rakendama, avaldama", "to apply force or influence"],
    explicit: ["selgesõnaline", "said openly, leaving nothing to be guessed"],
    exploit: ["ära kasutama", "to use something fully — or to use someone unfairly"],
    expose: ["paljastama; kokku puutuma", "to uncover; or to bring into contact with"],
    facilitate: ["hõlbustama", "to make easier"],
    feasible: ["teostatav", "possible to do"],
    finite: ["piiratud, lõplik", "having an end; not unlimited"],
    fluctuate: ["kõikuma", "to go up and down"],
    forecast: ["prognoos", "a statement about what will happen"],
    formulate: ["sõnastama", "to put into a clear form of words"],
    fundamental: ["põhiline, alusepanev", "the most basic and important"],
    generate: ["tekitama, looma", "to make or produce"],
    genuine: ["tõeline, ehtne", "real, not fake"],
    guarantee: ["tagatis, garantii", "a firm promise"],
    hierarchy: ["hierarhia, astmestik", "an order from highest to lowest"],
    hypothesis: ["hüpotees", "an idea you test to see if it is true"],
    identical: ["identne, täpselt sama", "exactly the same"],
    illustrate: ["näitlikustama", "to make clear with an example"],
    imitate: ["jäljendama", "to copy"],
    implement: ["ellu viima, rakendama", "to actually carry out a plan"],
    implicit: ["kaudne, vaikimisi", "not said openly but understood"],
    imply: ["vihjama; tähendama", "to suggest without saying"],
    impose: ["peale suruma, kehtestama", "to force something on someone"],
    incentive: ["stiimul, ajend", "a reason that makes someone want to act"],
    incidence: ["esinemissagedus; langemine kellelegi", "how often something happens; or who really bears a cost"],
    incur: ["endale tekitama", "to bring a cost or loss on yourself"],
    indicate: ["osutama, näitama", "to show or point to"],
    induce: ["esile kutsuma", "to cause something to happen"],
    inevitable: ["vältimatu", "certain to happen; cannot be avoided"],
    infer: ["järeldama", "to work out from evidence"],
    inherent: ["olemuslik, loomuomane", "part of the nature of the thing"],
    inhibit: ["pidurdama", "to hold back"],
    initiate: ["algatama", "to start"],
    insight: ["arusaam, taipamine", "a true understanding that was not obvious"],
    integrate: ["lõimima, ühendama", "to join parts into one whole"],
    interpret: ["tõlgendama", "to decide what something means"],
    intervene: ["sekkuma", "to step in and change what is happening"],
    intrinsic: ["sisemine, olemuslik", "belonging to the thing itself"],
    isolate: ["eraldama", "to separate one thing from everything else"],
    justify: ["põhjendama", "to give good reasons for"],
    legitimate: ["õiguspärane, põhjendatud", "allowed, or reasonable"],
    liable: ["vastutav; kalduv", "legally responsible; or likely to"],
    magnitude: ["suurusjärk", "how big something is"],
    maintain: ["säilitama; väitma", "to keep as it is; or to insist"],
    mandate: ["volitus, mandaat", "official permission or instruction"],
    manipulate: ["manipuleerima", "to control someone unfairly"],
    margin: ["marginaal, vahe", "the gap between price and cost — or a narrow edge"],
    mediate: ["vahendama", "to act between two sides"],
    methodology: ["metoodika", "the set of methods used"],
    mitigate: ["leevendama", "to make less bad"],
    modify: ["muutma, kohandama", "to change slightly"],
    monitor: ["jälgima", "to watch over time"],
    motive: ["ajend, motiiv", "the reason someone does something"],
    mutual: ["vastastikune", "going both ways"],
    negligible: ["tühine", "so small it can be ignored"],
    notion: ["mõte, arusaam", "an idea"],
    obscure: ["ähmane; varjama", "hard to understand; or to hide"],
    obsolete: ["vananenud", "out of date and no longer used"],
    obtain: ["hankima, saama", "to get"],
    offset: ["tasakaalustama", "to cancel out with something on the other side"],
    optimal: ["optimaalne, parim võimalik", "the best possible"],
    outcome: ["tulemus", "what happens in the end"],
    overlap: ["kattuma", "to cover part of the same ground"],
    paradigm: ["paradigma, mõttemudel", "the whole way of thinking a field uses"],
    parameter: ["parameeter, muutuja", "a value you can set that changes the result"],
    partial: ["osaline; erapoolik", "only part of it; or taking one side"],
    perceive: ["tajuma", "to notice or understand through the senses"],
    persist: ["püsima; visalt jätkama", "to keep going or keep existing"],
    perspective: ["vaatenurk", "the point of view something is seen from"],
    pervasive: ["läbiv, kõikjale tungiv", "found everywhere"],
    phenomenon: ["nähtus", "a thing that happens and can be observed"],
    plausible: ["usutav", "sounds reasonable — which is not the same as true"],
    portion: ["osa", "a part of a whole"],
    potential: ["võimalik, potentsiaalne", "possible in the future but not yet real"],
    precede: ["eelnema", "to come before"],
    precise: ["täpne", "exact"],
    preliminary: ["esialgne", "coming first, before the main part"],
    premise: ["eeldus, lähtekoht", "something taken as true to build an argument on"],
    presume: ["eeldama", "to assume something is true"],
    prevail: ["valitsema; peale jääma", "to be most common, or to win in the end"],
    principle: ["põhimõte", "a basic rule that explains many cases"],
    procedure: ["menetlus, protseduur", "the official steps for doing something"],
    prohibit: ["keelama", "to forbid"],
    proportion: ["osakaal, proportsioon", "how big one part is compared with the whole"],
    prospect: ["väljavaade; potentsiaalne klient", "a possible future — or a possible customer"],
    provision: ["säte; varustamine", "a rule in an agreement; or supplying something"],
    pursue: ["taotlema, jälitama", "to chase or try to achieve"],
    qualitative: ["kvalitatiivne", "about qualities and descriptions, not numbers"],
    quantitative: ["kvantitatiivne", "about amounts and numbers"],
    radical: ["radikaalne, juurteni ulatuv", "going all the way to the root; extreme"],
    ratio: ["suhtarv", "one number divided by another"],
    rational: ["ratsionaalne, mõistuspärane", "based on reason"],
    reciprocal: ["vastastikune", "given in return, both ways"],
    reconcile: ["ühitama, lepitama", "to make two things fit together"],
    refine: ["viimistlema, täpsustama", "to improve by small careful changes"],
    refute: ["ümber lükkama", "to prove wrong"],
    reinforce: ["tugevdama", "to make stronger"],
    relevant: ["asjakohane", "connected to what is being discussed, and mattering to it"],
    reluctant: ["tõrges", "unwilling"],
    remedy: ["ravim; lahendus", "the cure or fix"],
    render: ["muutma (milleski); esitama", "to make something become a certain way"],
    residual: ["jääk", "what is left after you subtract everything you can explain"],
    resolve: ["lahendama; otsustavus", "to settle a problem; or firmness of purpose"],
    respective: ["vastav", "each belonging to the one just named"],
    restrain: ["ohjeldama", "to hold back"],
    retain: ["säilitama, alles hoidma", "to keep"],
    reveal: ["paljastama", "to show something that was hidden"],
    revenue: ["tulu, käive", "the money coming in, before costs"],
    rigid: ["jäik", "not able to bend or change"],
    rigour: ["rangus, põhjalikkus", "being careful, exact and honest in method"],
    scarce: ["nappiv, vähene", "not enough to go round"],
    scenario: ["stsenaarium", "one possible way things could turn out"],
    scope: ["ulatus, haare", "how much ground something covers"],
    scrutiny: ["põhjalik kontroll", "close and critical examination"],
    sequence: ["järjestus", "the order things come in"],
    sophisticated: ["keerukas, viimistletud", "advanced and complex"],
    spectrum: ["skaala, spekter", "a full range between two extremes"],
    speculate: ["oletama; spekuleerima", "to guess without evidence"],
    stagnant: ["seisev, paigal tammuv", "not moving or growing"],
    stake: ["panus; osalus", "what you stand to win or lose"],
    stance: ["seisukoht", "the position someone takes"],
    straightforward: ["otsekohene, lihtne", "simple and clear"],
    subordinate: ["alluv; allutatud", "lower in rank, or made less important"],
    subsequent: ["järgnev", "coming after"],
    subsidy: ["toetus, subsiidium", "money the state pays to lower a price"],
    substantial: ["märkimisväärne, sisuline", "large or real enough to matter"],
    subtle: ["peen, raskesti märgatav", "small and easy to miss, but important"],
    sufficient: ["piisav", "enough"],
    superfluous: ["üleliigne", "more than is needed; unnecessary"],
    sustain: ["ülal hoidma, säilitama", "to keep something going"],
    tangible: ["käegakatsutav", "can be touched; real and concrete"],
    tentative: ["esialgne, ettevaatlik", "not final; held lightly"],
    threshold: ["lävi, künnis", "the point at which something starts to happen"],
    transfer: ["ülekanne, üle kandma", "to move from one place or context to another"],
    transition: ["üleminek", "the change from one state to another"],
    trigger: ["vallandama; päästik", "to set off; or the thing that sets it off"],
    trivial: ["tühine", "so small or obvious it does not matter"],
    ultimate: ["lõplik, kõige tähtsam", "final, or most important"],
    undergo: ["läbi tegema", "to go through something, usually unpleasant"],
    underlying: ["aluseks olev", "hidden beneath, and causing what you can see"],
    undertake: ["ette võtma", "to take on a task"],
    unprecedented: ["enneolematu", "never having happened before"],
    valid: ["kehtiv, põhjendatud", "correctly reasoned, or legally in force"],
    viable: ["elujõuline", "able to work and survive"],
    violate: ["rikkuma", "to break a rule or agreement"],
    voluntary: ["vabatahtlik", "done by choice, not forced"],
    widespread: ["laialt levinud", "found over a wide area"],
    yield: ["andma, tootma; järele andma", "to produce a result; or to give way"],

    bankruptcy: ["pankrot", "when a company cannot pay its debts and the courts take over"],
    creditor: ["võlausaldaja", "someone the company owes money to"],
    debt: ["võlg", "money that must be paid back, usually with interest"],
    metric: ["mõõdik", "the particular number you choose to measure something by"],
    overhead: ["püsikulud", "the costs that continue whether or not you sell anything"],
    liquidate: ["likvideerima", "to sell everything off and close the company"],
    milestone: ["verstapost", "a point along the way that is worth marking"],
    contemporary: ["tolleaegne; kaasaegne", "from the same time as the events described"],
    dismissible: ["kõrvaleheidetav", "easy to decide is not worth attention"],
    immovable: ["liikumatu, kõigutamatu", "impossible to shift"],
    niche: ["nišš", "a small specialised part of a market"],
    primary: ["peamine, põhiline", "the main one — as in the bank you actually get paid into"],
    secondary: ["teisene, kõrval-", "not the main one"],
    deposit: ["hoius", "money left with a bank"],
    lease: ["üürileping", "a long contract to rent premises, which must be paid either way"],
    ceiling: ["lagi, ülempiir", "the highest something can go"],
    approximation: ["ligikaudne hinnang", "a figure that is close enough to be useful but not exact"],
    interrogate: ["üle kuulama, kriitiliselt küsitlema", "to question something hard instead of accepting it"],
    /* words this course leans on especially hard */
    myopia: ["lühinägelikkus", "short-sightedness — seeing what is close and missing what is further"],
    hyperopia: ["kaugnägelikkus", "long-sightedness — the opposite error"],
    incumbent: ["turgu valitsev olemasolev ettevõte", "the company already holding the market"],
    complacency: ["eneserahulolu", "feeling safe when you have no good reason to be"],
    deception: ["pettus", "making someone believe something untrue"],
    diagnose: ["diagnoosima", "to work out what is actually wrong, the way a doctor does"],
    diagnostic: ["diagnostiline vahend", "a tool for finding out what is wrong"],
    intermediary: ["vahendaja", "someone in the middle between maker and buyer"],
    procurement: ["hanked, ostuosakond", "the formal process organisations use to buy things"],
    endorsement: ["heakskiit, soovitus", "a public statement of support that lends you trust"],
    sceptical: ["skeptiline, kahtlev", "not easily convinced; wanting proof"],
    stalled: ["takerdunud", "stopped making progress without anyone deciding to stop"],
    exchange: ["vahetus", "two parties each giving the other something they value more"],
    offering: ["pakkumine", "whatever you put in front of someone: product, service, idea"],
    discipline: ["valdkond, distsipliin", "a field of study with its own methods"],
    compounding: ["liitumine, kuhjumine", "growth that multiplies each period instead of adding"],
    exponent: ["astendaja", "the small raised number saying how many times to multiply"],
    logarithm: ["logaritm", "the tool that answers: how many times must I multiply by this?"],
    denominator: ["nimetaja", "the bottom number of a fraction — what you are dividing by"],
    numerator: ["lugeja", "the top number of a fraction"],
    elasticity: ["elastsus", "how much one thing changes when another changes"],
    externality: ["välismõju", "a cost or benefit falling on someone outside the deal"],
    proxy: ["asendusnäitaja", "something measurable you use to stand for something you cannot measure"],
    heuristic: ["rusikareegel", "a mental shortcut that is usually good enough"],
    salience: ["esiletulevus, meeldejäävus", "how easily something comes to mind"],
    attrition: ["kulumine, äravool", "steady loss over time"],
    leverage: ["finantsvõimendus; mõjujõud", "using borrowed money; or the power to move something"],
    arbitrage: ["arbitraaž", "buying cheap in one place and selling dear in another"],

    /* week-2 marketing and the economics course */
    ability: ["võimekus", "Here, the qualities of a person that affect both their schooling and their earnings."],
    absolute: ["absoluutne", "Measured on its own, not against anything else."],
    abstraction: ["abstraktsioon, üldistus", "Leaving things out on purpose to see the shape of what remains."],
    acquirer: ["vastuvõttev pank", "The bank or firm that signs up the shop and pays it for card sales."],
    adjustment: ["kohanemine", "The slow, costly process of people and firms moving to new work."],
    administrative: ["haldusandmed", "Coming from records kept for another purpose — tax, benefits, customs."],
    asset: ["vara, väärtus", "Something valuable the company owns or has built."],
    assignment: ["jaotus, määramine", "How units came to be in the treated group rather than the untreated one."],
    assumption: ["eeldus", "Something believed without being checked, usually without noticing."],
    attainable: ["saavutatav", "Possible to reach with what you have now."],
    austerity: ["kokkuhoiupoliitika", "Government policy of cutting spending and raising taxes to reduce debt."],
    barrier: ["tõke, barjäär", "Anything that makes it hard or expensive for a new company to enter."],
    baseline: ["lähtetase", "The starting level, before anything happens."],
    basket: ["korv, tarbimiskorv", "The fixed list of goods whose prices are tracked to measure inflation."],
    calibrate: ["kalibreerima, häälestama", "To set a model's numbers so it matches the world you are studying."],
    candid: ["avameelne, aus", "Honest, even when the honesty is unwelcome."],
    cannibalise: ["omaenda müüki sööma", "To take sales from your own existing product with a new one."],
    capability: ["võimekus", "Something a firm is genuinely able to do well, better than others can."],
    catchment: ["teeninduspiirkond", "The area a shop or a branch actually draws its customers from."],
    causation: ["põhjuslikkus", "One thing actually bringing another about, not just appearing alongside it."],
    coefficient: ["kordaja, koefitsient", "The number attached to a variable, saying how much the outcome moves with it."],
    commitment: ["kohustus, lubadus", "A promise that binds you, which can be valuable precisely because it is hard to escape."],
    comparative: ["võrdlev, suhteline", "Measured against something else — here, against what you give up."],
    complier: ["järgija, mõjutatu", "Someone whose treatment actually changed because of the instrument."],
    confounder: ["segav tegur", "A third thing causing both of the things you are comparing."],
    consensus: ["üksmeel", "Broad agreement among people who study the question."],
    consolidation: ["koondumine", "Many companies becoming few, usually by buying each other."],
    constraint: ["piirang", "A limit you cannot exceed — time, money, capacity."],
    contaminate: ["saastama, rikkuma", "To spoil something by getting into it."],
    contested: ["vaieldav", "Still genuinely argued about by serious people."],
    correlation: ["korrelatsioon, seos", "Two things moving together in the data."],
    counterfactual: ["vastandfakt, teisiti-stsenaarium", "What would have happened otherwise. Never observed, always needed."],
    crossover: ["ristumiskoht", "The moment two lines on a chart meet and swap places."],
    deduplicated: ["dubleerimisest puhastatud", "Counted once per person even if they appear several times in the data."],
    demand: ["nõudlus", "People wanting something AND being able and willing to pay for it."],
    demographic: ["demograafiline", "To do with the make-up of a population — ages, incomes, household sizes."],
    discontinuity: ["katkestus, hüpe", "A sudden jump at a particular point."],
    dismiss: ["kõrvale heitma", "To decide something is not worth paying attention to."],
    distortion: ["moonutus", "A word for something moving a market away from a reference point — and the reference point is a choice."],
    divisible: ["jaotatav", "Able to be split into small pieces, so you can do a little more or a little less."],
    domiciled: ["registreeritud, asukohaga", "Legally based in a country, which may have nothing to do with where the work happens."],
    dominance: ["turgu valitsev seisund", "Holding so large a share that you set the terms."],
    durable: ["püsiv, kestev", "Lasts a long time without changing."],
    ecosystem: ["ökosüsteem", "A product plus everything built around it — apps, accessories, partners — that makes it worth more."],
    efficient: ["tõhus, efektiivne", "Producing as much as possible from the resources available — with no waste."],
    elicit: ["esile kutsuma", "To draw something out, usually an answer or a reaction."],
    eligible: ["kõlblik, õigustatud", "Qualifying under the rule."],
    endogenous: ["sisemiselt määratud", "Determined inside the system you are studying, rather than imposed from outside."],
    escalate: ["eskaleeruma, kasvama", "To grow larger and harder to stop."],
    ethics: ["eetika", "Whether it is right to do something, regardless of whether it would work."],
    expectations: ["ootused", "What people believe is coming, which changes what they do now."],
    external: ["väline", "Outside the company — things it can only respond to."],
    fallacy: ["eksiarvamus, vigane arutlus", "A way of reasoning that feels right and is wrong."],
    forgo: ["loobuma", "To give something up, usually in order to have something else."],
    frontier: ["piir, äär", "The outer edge of what is possible with what you have."],
    generalise: ["üldistama", "To extend a finding from where it was measured to somewhere else."],
    gross: ["bruto", "Before deductions such as tax. The opposite is net."],
    hardware: ["riistvara", "The physical machine, as opposed to the programs that run on it."],
    hypothetical: ["oletuslik, hüpoteetiline", "Imagined for the sake of an argument, not real."],
    idle: ["jõude, kasutamata", "Sitting unused."],
    impersonate: ["kellegi teisena esinema", "To pretend to be someone you are not."],
    increment: ["juurdekasv, lisaühik", "One small addition."],
    instrument: ["instrument", "Something that pushes people into treatment but has no other route to the outcome."],
    intelligence: ["luureteave, koondinfo", "Collected information about rivals and markets, used to decide."],
    interchange: ["vahendustasu", "The fee that moves from the shop's bank to the cardholder's bank on every card payment."],
    internal: ["sisemine", "Inside the company — things it owns or controls."],
    interoperable: ["koostalitlusvõimeline", "Able to work with someone else's system."],
    irreversible: ["pöördumatu", "Cannot be undone once done."],
    issuer: ["kaardi väljaandja", "The bank that gives you your card and lends you the money on it."],
    liability: ["kohustus, koormis", "Something that costs you or holds you back."],
    lumpy: ["tükiline, suurte sammudega", "Only available in big pieces — you cannot buy half a factory."],
    macro: ["makro-, üldine", "Large-scale, about the whole system rather than one company."],
    marginal: ["piirne, marginaalne", "To do with one more unit — the next one, not the whole lot."],
    median: ["mediaan", "The middle value: half are above it, half below. Often more honest than an average."],
    monopsony: ["monopson, ainuostja", "A market with one big buyer — here, an employer with power to set wages below what competition would give."],
    mutually: ["vastastikku", "In a way that applies to both sides."],
    noise: ["müra", "Random variation with no meaning."],
    normative: ["hinnanguline, normatiivne", "About what ought to be. Requires a judgement about what matters."],
    notional: ["mõtteline, arvestuslik", "Existing as an idea rather than as a payment. Real, but not banked."],
    null: ["nullhüpotees", "The default assumption being tested against — usually that the effect is zero."],
    obtainable: ["saavutatav, kättesaadav", "Able to be got in practice, not just in theory."],
    omit: ["välja jätma", "To leave out."],
    option: ["optsioon, valikuvõimalus", "A small commitment that buys you the right to act later without forcing you to."],
    parity: ["võrdsus, samal tasemel olek", "Being equal to the others. Not an advantage, just a ticket to compete."],
    peripheral: ["kõrvaline, äärealane", "At the edge, treated as unimportant."],
    perishable: ["riknev, kaduv", "Something that loses all its value at a deadline. An empty seat at take-off is worth nothing forever."],
    positive: ["kirjeldav, positiivne", "About what is or what would happen. Checkable, at least in principle."],
    "pre-register": ["eelregistreerima", "To state publicly what you will test before you look at the data."],
    precision: ["täpsus", "How tightly an estimate is pinned down. High precision can still be precisely wrong."],
    prediction: ["ennustus", "A statement about what will happen that could turn out wrong."],
    prescription: ["soovitus, ettekirjutus", "The action a theory recommends you take."],
    productivity: ["tootlikkus", "How much output an hour of work produces."],
    profile: ["profiil, iseloomustus", "A short description of what someone is like and how they behave."],
    proprietary: ["ärisaladus, omanduslik", "Owned privately and not meant to be shared."],
    provisional: ["esialgne", "First version, expected to change."],
    quadrant: ["kvadrant, veerand", "One of the four boxes made by crossing two axes."],
    randomise: ["juhuslikustama", "To decide by chance who gets the treatment, so the groups differ only by luck."],
    reallocate: ["ümber jaotama", "To move resources from one use to another."],
    recoverable: ["tagasisaadav", "Able to be got back."],
    regression: ["regressioon", "A method for fitting a line through data to summarise how things move together."],
    regulation: ["regulatsioon, reeglistik", "Rules made by a government or authority that companies must obey."],
    replicate: ["korrata, reprodutseerida", "To repeat a study and see whether the same result comes out."],
    retaliate: ["vastu lööma, kätte maksma", "To hit back after being attacked."],
    revision: ["korrigeerimine, parandus", "An updated figure published when better information arrives."],
    rival: ["konkurent, rivaal", "A company competing for the same customer or the same money."],
    robust: ["vastupidav, töökindel", "Still true even when the details change."],
    robustness: ["vastupidavus", "Whether a result survives reasonable changes to how it was computed."],
    scanning: ["skaneerimine, ringivaatamine", "Looking widely and cheaply for anything that might matter later."],
    scarcity: ["nappus, piiratus", "There is not enough of something to satisfy everyone who wants it at a price of zero."],
    selection: ["valikuefekt", "People ending up in a group for reasons connected to the outcome you are measuring."],
    "self-deception": ["enesepettus", "Believing something about yourself that is not true, without meaning to lie."],
    signal: ["signaal, märguanne", "An early, faint sign of a change that has not arrived yet."],
    significant: ["statistiliselt oluline", "In statistics, unlikely to be produced by chance alone. Not the same as large or important."],
    simplify: ["lihtsustama", "To make less complicated by removing detail."],
    slope: ["kalle, tõus", "How steeply a line falls or rises: how much of one thing you lose per unit of the other."],
    smuggle: ["salaja sisse tooma", "To carry something in hidden, so nobody inspects it."],
    specialise: ["spetsialiseeruma", "To concentrate on one thing instead of doing a bit of everything."],
    specification: ["mudeli täpsustus", "The exact choice of variables and form used in an estimate."],
    spreadsheet: ["tabelarvutus", "The file the calculations were done in."],
    spurious: ["näiline, petlik", "Looking like a real relationship and not being one."],
    stagflation: ["stagflatsioon", "High inflation and high unemployment at the same time — which the old model said was impossible."],
    stall: ["seiskuma, takerduma", "To stop making progress without anyone deciding to stop."],
    structure: ["struktuur, ülesehitus", "The permanent shape of an industry — how many rivals, how easy to enter, who depends on whom."],
    substitute: ["asendaja, aseaine", "A different kind of product that does the same job for the customer."],
    sunk: ["pöördumatult kulutatud", "Already spent and impossible to get back."],
    survey: ["küsitlus, uuring", "Asking a sample of people or firms and scaling the answers up."],
    switching: ["vahetamine, ümberlülitumine", "Moving from one supplier to another, and what it costs you to do so."],
    tractable: ["käsitletav, jõukohane", "Simple enough to actually work with."],
    "trade-off": ["kompromiss, vahetus", "Getting more of one thing by accepting less of another."],
    trap: ["lõks", "Something that looks like safety and turns out to hold you in place."],
    treatment: ["sekkumine, mõjutus", "Whatever is being done — a policy, a drug, a course. The thing whose effect you want."],
    trend: ["trend, suund", "The direction something was already moving in."],
    variance: ["hajuvus, dispersioon", "How spread out a set of numbers is."],
    volatile: ["kiiresti muutuv, kõikuv", "Changes fast and unpredictably."],
    weight: ["kaal, osatähtsus", "How much importance one item gets in an average."],
    weighting: ["kaalumine", "Deciding how much each observation counts in an average."],
    orientation: ["suunitlus, hoiak", "the direction a company faces — what it puts first"],
    reflex: ["refleks, automaatne reaktsioon", "something you do without thinking about it"],
    expiry: ["aegumine", "the moment something stops being valid or good"],
    seductive: ["ahvatlev", "very attractive in a way that pulls you in"],
    prestige: ["prestiiž, maine", "the respect something gets for looking high-status"],
    commission: ["komisjonitasu; tellimus", "a fee paid for making a sale; or an order to make something"],
    overcapacity: ["ületootmisvõimsus", "being able to make far more than anyone wants to buy"],
    unsought: ["mitteotsitav", "not looked for — you only think about it when you must"],
    articulate: ["sõnastama, selgelt väljendama", "to put something into clear words"],
    distinctive: ["eristuv, äratuntav", "easy to tell apart from the rest"],
    deprivation: ["ilmajäetus, puudus", "not having something you need"],
    checkout: ["kassa, ostu lõpetamine", "the last step of buying, where you pay"],
    friction: ["hõõrdumine, takistus", "the small annoyances that slow a person down"],
    conversion: ["konverteerimine; ostuks muutumine", "turning an interested person into a buyer"],
    expectation: ["ootus", "what a person believes will happen"],
    disconfirmation: ["ootuste mittetäitumine", "when what happens does not match what you expected"],
    delight: ["vaimustus, rõõm", "a happy surprise, more than being merely satisfied"],
    utility: ["kasulikkus", "how much use or benefit something gives you"],
    haggling: ["tingimine, kauplemine", "arguing back and forth about the price"],
    flatter: ["meelitama", "to say nice things to please someone"],
    architecture: ["ülesehitus, arhitektuur", "how the parts of something are arranged"],
    markdown: ["hinnaalandus", "cutting a price below the one first asked"],
    ritual: ["rituaal, kombetalitus", "something people repeat the same way every time"],
    comparable: ["võrreldav", "similar enough to be measured against each other"],
    intangible: ["immateriaalne, katsumatu", "real but impossible to touch"],
    simultaneous: ["üheaegne", "happening at the same time"],
    discretion: ["otsustusvabadus; diskreetsus", "the freedom to decide for yourself"],
    mnemonic: ["meeldejätmisvõte", "a trick that helps you remember"]
  };
  /* index is lower-case; simple endings are matched at look-up time */
  var out = {};
  Object.keys(d).forEach(function (k) { out[k] = { et: d[k][0], en: d[k][1] }; });
  return out;
})();
